### ISSUE TITLE
Log-in/Sign-up not working

### ISSUE THREAD

**Issue by elisiariocouto** [haswalt/docker-healthchecks#2]
Hello. I've pulled the latest version of the Docker Image and I can not log-in. Everytime I put my e-mail in the login page, I get the following traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/djmail/core.py", line 48, in _safe_send_message
    sended = connection.send_messages([email])
  File "/usr/local/lib/python3.5/dist-packages/django/core/mail/backends/console.py", line 36, in send_messages
    self.write_message(message)
  File "/usr/local/lib/python3.5/dist-packages/django/core/mail/backends/console.py", line 23, in write_message
    self.stream.write('%s\n' % msg_data)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 5084: ordinal not in range(128)
```

Also, are there any default credentials on the Django Admin page?

**Comment by haswalt** [comment]
Hi @elisiariocouto,

i'm sorry you are having issues with the application. There are no default credentials for the Django Admin. As per the documentation over at the main [healthchecks](https://github.com/healthchecks/healthchecks#setting-up-for-development) repo you need to run the following command inside your docker container:

```
./manage.py createsuperuser
```

Can you provide me with any extra configuration or environment variables you passed to the container when you launched it please.

**Comment by elisiariocouto** [comment]
This is my `docker run`:
```
docker run -d -p 9090:9090 \
    -e HEALTHCHECKS_DEBUG=False \
    -e HEALTHCHECKS_HOST=REDACTED \
    -e HEALTHCHECKS_EMAIL_FROM="<email>" \
    -e HEALTHCHECKS_EMAIL_HOST="smtp.mailgun.org" \
    -e HEALTHCHECKS_EMAIL_PORT="25" \
    -e HEALTHCHECKS_EMAIL_USER="postmaster@mailgun.REDACTED" \
    -e HEALTHCHECKS_EMAIL_PASSWORD="REDACTED" \
    haswalt/docker-healthchecks
```

Thanks for the quick reply.

**Comment by haswalt** [comment]
hi @elisiariocouto 

can you confirm that port 25 is not blocked by any firewalls and that the mailgun details are correct? I have no problems testing against mailgun here.

The error you see is complaining about invalid characters, more acurately right single quote:

Are you running on windows?
Does your email contain any special characters?
Does your from email contain any special characters?

can you also try puling the latest version that was uploaded yesterday and try with that too?

**Comment by elisiariocouto** [comment]
Latest version works like a charm. Thanks 👍
