### ISSUE TITLE
Send Alerts

### ISSUE THREAD

**Issue by elisiariocouto** [haswalt/docker-healthchecks#3]
Is the `./manage.py sendalerts` active on the docker image?

**Comment by haswalt** [comment]
Hi @elisiariocouto at the moment no it is not. I can look at adding it

**Comment by cuu508** [comment]
An interesting option is to let uwsgi manage the sendalerts command (`--attach-daemon`). This way, whenever the web server runs, sendalerts will also be running. 

It is safe to have multiple concurrent `manage.py sendalerts` processes running.
